apiVersion: apps/v1
kind: Deployment
metadata:
  name: qna-chatbot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qna-chatbot
  template:
    metadata:
      labels:
        app: qna-chatbot
    spec:
      containers:
      - name: qna-chatbot
        image: your-docker-username/qa-chatbot:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: qna-chatbot-service
spec:
  selector:
    app: qna-chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
